import 'package:pkg_dinh_nghia_ss020/dinh_nghia_thanh_phan_define.dart';
/// -----
/// TODO:
/// -----
class DiemToaDoChiTietPhamViDenHang50 {
  List<DiemToaDoCoBan> danhSachToaDo = [];

  Future<void> onInitList() async {
    await hamKhoiTaoToaDoChiTietHang41();
    await hamKhoiTaoToaDoChiTietHang42();
    await hamKhoiTaoToaDoChiTietHang43();
    await hamKhoiTaoToaDoChiTietHang44();
    await hamKhoiTaoToaDoChiTietHang45();
    await hamKhoiTaoToaDoChiTietHang46();
    await hamKhoiTaoToaDoChiTietHang47();
    await hamKhoiTaoToaDoChiTietHang48();
    await hamKhoiTaoToaDoChiTietHang49();
    await hamKhoiTaoToaDoChiTietHang50();
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang41() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 41);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 41);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 41);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 41);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 41);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 41);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 41);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 41);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 41);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 41);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 41);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 41);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 41);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 41);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 41);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 41);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 41);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 41);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 41);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 41);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 41);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 41);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 41);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 41);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 41);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 41);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 41);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 41);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 41);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 41);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 41);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 41);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 41);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 41);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 41);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 41);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 41);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 41);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 41);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 41);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 41);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 41);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 41);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 41);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 41);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 41);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 41);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 41);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 41);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 41);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 41);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 41);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 41);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 41);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang41_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 41);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang42() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 42);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 42);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 42);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 42);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 42);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 42);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 42);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 42);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 42);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 42);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 42);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 42);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 42);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 42);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 42);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 42);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 42);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 42);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 42);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 42);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 42);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 42);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 42);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 42);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 42);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 42);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 42);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 42);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 42);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 42);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 42);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 42);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 42);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 42);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 42);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 42);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 42);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 42);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 42);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 42);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 42);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 42);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 42);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 42);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 42);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 42);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 42);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 42);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 42);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 42);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 42);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 42);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 42);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 42);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang42_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 42);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang43() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 43);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 43);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 43);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 43);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 43);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 43);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 43);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 43);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 43);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 43);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 43);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 43);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 43);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 43);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 43);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 43);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 43);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 43);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 43);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 43);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 43);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 43);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 43);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 43);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 43);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 43);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 43);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 43);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 43);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 43);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 43);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 43);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 43);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 43);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 43);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 43);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 43);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 43);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 43);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 43);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 43);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 43);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 43);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 43);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 43);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 43);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 43);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 43);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 43);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 43);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 43);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 43);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 43);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 43);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang43_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 43);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang44() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 44);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 44);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 44);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 44);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 44);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 44);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 44);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 44);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 44);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 44);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 44);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 44);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 44);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 44);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 44);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 44);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 44);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 44);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 44);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 44);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 44);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 44);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 44);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 44);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 44);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 44);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 44);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 44);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 44);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 44);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 44);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 44);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 44);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 44);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 44);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 44);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 44);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 44);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 44);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 44);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 44);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 44);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 44);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 44);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 44);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 44);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 44);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 44);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 44);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 44);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 44);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 44);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 44);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 44);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang44_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 44);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang45() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 45);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 45);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 45);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 45);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 45);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 45);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 45);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 45);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 45);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 45);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 45);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 45);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 45);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 45);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 45);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 45);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 45);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 45);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 45);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 45);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 45);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 45);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 45);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 45);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 45);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 45);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 45);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 45);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 45);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 45);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 45);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 45);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 45);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 45);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 45);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 45);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 45);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 45);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 45);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 45);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 45);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 45);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 45);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 45);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 45);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 45);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 45);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 45);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 45);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 45);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 45);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 45);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 45);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 45);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang45_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 45);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang46() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 46);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 46);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 46);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 46);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 46);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 46);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 46);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 46);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 46);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 46);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 46);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 46);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 46);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 46);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 46);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 46);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 46);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 46);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 46);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 46);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 46);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 46);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 46);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 46);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 46);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 46);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 46);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 46);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 46);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 46);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 46);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 46);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 46);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 46);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 46);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 46);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 46);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 46);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 46);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 46);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 46);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 46);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 46);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 46);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 46);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 46);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 46);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 46);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 46);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 46);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 46);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 46);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 46);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 46);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang46_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 46);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang47() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 47);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 47);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 47);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 47);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 47);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 47);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 47);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 47);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 47);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 47);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 47);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 47);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 47);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 47);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 47);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 47);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 47);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 47);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 47);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 47);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 47);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 47);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 47);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 47);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 47);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 47);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 47);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 47);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 47);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 47);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 47);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 47);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 47);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 47);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 47);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 47);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 47);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 47);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 47);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 47);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 47);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 47);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 47);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 47);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 47);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 47);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 47);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 47);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 47);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 47);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 47);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 47);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 47);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 47);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang47_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 47);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang48() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 48);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 48);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 48);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 48);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 48);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 48);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 48);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 48);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 48);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 48);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 48);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 48);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 48);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 48);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 48);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 48);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 48);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 48);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 48);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 48);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 48);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 48);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 48);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 48);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 48);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 48);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 48);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 48);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 48);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 48);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 48);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 48);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 48);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 48);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 48);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 48);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 48);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 48);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 48);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 48);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 48);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 48);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 48);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 48);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 48);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 48);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 48);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 48);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 48);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 48);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 48);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 48);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 48);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 48);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang48_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 48);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang49() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 49);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 49);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 49);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 49);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 49);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 49);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 49);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 49);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 49);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 49);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 49);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 49);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 49);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 49);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 49);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 49);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 49);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 49);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 49);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 49);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 49);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 49);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 49);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 49);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 49);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 49);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 49);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 49);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 49);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 49);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 49);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 49);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 49);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 49);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 49);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 49);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 49);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 49);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 49);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 49);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 49);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 49);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 49);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 49);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 49);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 49);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 49);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 49);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 49);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 49);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 49);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 49);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 49);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 49);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang49_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 49);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  Future<void> hamKhoiTaoToaDoChiTietHang50() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 50);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 50);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 50);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 50);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 50);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 50);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 50);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 50);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 50);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 50);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 50);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 50);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 50);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 50);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 50);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 50);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 50);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 50);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 50);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 50);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 50);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 50);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 50);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 50);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 50);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 50);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 50);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 50);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 50);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 50);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 50);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 50);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 50);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 50);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 50);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 50);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 50);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 50);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 50);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 50);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 50);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 50);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 50);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 50);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 50);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 50);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 50);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 50);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 50);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 50);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 50);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 50);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 50);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 50);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang50_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 50);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }
}
