name: pkg_man_hinh_ss00420
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  pkg_dinh_nghia_ss020:
    path: ../pkg_dinh_nghia_ss020
  pkg_dinh_nghia_ss028:
    path: ../pkg_dinh_nghia_ss028
  pkg_dinh_nghia_ss050:
    path: ../pkg_dinh_nghia_ss050

  pkg_man_hinh_ss00028d:
    path: ../pkg_man_hinh_ss00028d

  provider: 6.0.2

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    # _____[Nut_Chuyen_Man_Hinh_SS01]_____
    - lib/24_def0024/ADef20_0/08_SubDefs/Def20_2/08_SubDefs/Def20_4/08_SubDefs/Def30_6/06_ImgSrcs/nut_bam_chuyen_man_hinh_ss01.png
    # _____[Nut_Chuyen_Man_Hinh_SS02]_____
    - lib/24_def0024/ADef20_0/08_SubDefs/Def20_2/08_SubDefs/Def20_4/08_SubDefs/Def32_6/06_ImgSrcs/nut_bam_chuyen_man_hinh_ss02.png
    # _____[Nut_Chuyen_Man_Hinh_SS03]_____
    - lib/24_def0024/ADef20_0/08_SubDefs/Def20_2/08_SubDefs/Def20_4/08_SubDefs/Def34_6/06_ImgSrcs/nut_bam_chuyen_man_hinh_ss03.png
    # _____[Nut_Bam_Dong_Man_Hinh]_____
    - lib/24_def0024/ADef20_0/08_SubDefs/Def20_2/08_SubDefs/Def20_4/08_SubDefs/Def40_6/06_ImgSrcs/nut_bam_dong_man_hinh.png

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
