import 'package:pkg_dinh_nghia_ss020/dinh_nghia_thanh_phan_define.dart';
/// -----
/// TODO:
/// -----
class DiemToaDoChiTietPhamViDenHang60 {
  List<DiemToaDoCoBan> danhSachToaDo = [];

  Future<void> onInitList() async {
    await hamKhoiTaoToaDoChiTietHang51();
    await hamKhoiTaoToaDoChiTietHang52();
    await hamKhoiTaoToaDoChiTietHang53();
    await hamKhoiTaoToaDoChiTietHang54();
    await hamKhoiTaoToaDoChiTietHang55();
    await hamKhoiTaoToaDoChiTietHang56();
    await hamKhoiTaoToaDoChiTietHang57();
    await hamKhoiTaoToaDoChiTietHang58();
    await hamKhoiTaoToaDoChiTietHang59();
    await hamKhoiTaoToaDoChiTietHang60();
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang51() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 51);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 51);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 51);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 51);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 51);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 51);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 51);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 51);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 51);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 51);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 51);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 51);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 51);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 51);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 51);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 51);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 51);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 51);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 51);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 51);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 51);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 51);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 51);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 51);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 51);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 51);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 51);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 51);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 51);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 51);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 51);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 51);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 51);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 51);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 51);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 51);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 51);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 51);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 51);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 51);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 51);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 51);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 51);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 51);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 51);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 51);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 51);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 51);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 51);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 51);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 51);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 51);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 51);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 51);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang51_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 51);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang52() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 52);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 52);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 52);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 52);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 52);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 52);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 52);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 52);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 52);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 52);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 52);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 52);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 52);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 52);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 52);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 52);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 52);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 52);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 52);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 52);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 52);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 52);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 52);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 52);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 52);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 52);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 52);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 52);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 52);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 52);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 52);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 52);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 52);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 52);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 52);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 52);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 52);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 52);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 52);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 52);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 52);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 52);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 52);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 52);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 52);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 52);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 52);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 52);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 52);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 52);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 52);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 52);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 52);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 52);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang52_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 52);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang53() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 53);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 53);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 53);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 53);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 53);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 53);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 53);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 53);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 53);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 53);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 53);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 53);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 53);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 53);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 53);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 53);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 53);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 53);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 53);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 53);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 53);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 53);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 53);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 53);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 53);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 53);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 53);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 53);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 53);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 53);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 53);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 53);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 53);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 53);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 53);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 53);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 53);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 53);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 53);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 53);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 53);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 53);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 53);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 53);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 53);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 53);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 53);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 53);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 53);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 53);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 53);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 53);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 53);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 53);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang53_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 53);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang54() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 54);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 54);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 54);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 54);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 54);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 54);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 54);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 54);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 54);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 54);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 54);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 54);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 54);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 54);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 54);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 54);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 54);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 54);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 54);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 54);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 54);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 54);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 54);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 54);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 54);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 54);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 54);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 54);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 54);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 54);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 54);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 54);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 54);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 54);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 54);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 54);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 54);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 54);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 54);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 54);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 54);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 54);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 54);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 54);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 54);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 54);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 54);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 54);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 54);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 54);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 54);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 54);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 54);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 54);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang54_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 54);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang55() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 55);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 55);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 55);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 55);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 55);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 55);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 55);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 55);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 55);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 55);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 55);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 55);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 55);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 55);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 55);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 55);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 55);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 55);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 55);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 55);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 55);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 55);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 55);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 55);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 55);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 55);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 55);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 55);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 55);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 55);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 55);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 55);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 55);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 55);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 55);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 55);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 55);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 55);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 55);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 55);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 55);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 55);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 55);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 55);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 55);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 55);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 55);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 55);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 55);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 55);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 55);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 55);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 55);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 55);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang55_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 55);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang56() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 56);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 56);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 56);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 56);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 56);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 56);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 56);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 56);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 56);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 56);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 56);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 56);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 56);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 56);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 56);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 56);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 56);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 56);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 56);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 56);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 56);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 56);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 56);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 56);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 56);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 56);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 56);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 56);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 56);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 56);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 56);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 56);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 56);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 56);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 56);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 56);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 56);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 56);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 56);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 56);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 56);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 56);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 56);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 56);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 56);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 56);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 56);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 56);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 56);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 56);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 56);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 56);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 56);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 56);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang56_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 56);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang57() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 57);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 57);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 57);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 57);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 57);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 57);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 57);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 57);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 57);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 57);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 57);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 57);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 57);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 57);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 57);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 57);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 57);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 57);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 57);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 57);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 57);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 57);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 57);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 57);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 57);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 57);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 57);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 57);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 57);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 57);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 57);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 57);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 57);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 57);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 57);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 57);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 57);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 57);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 57);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 57);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 57);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 57);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 57);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 57);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 57);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 57);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 57);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 57);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 57);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 57);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 57);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 57);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 57);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 57);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang57_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 57);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang58() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 58);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 58);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 58);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 58);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 58);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 58);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 58);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 58);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 58);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 58);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 58);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 58);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 58);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 58);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 58);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 58);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 58);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 58);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 58);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 58);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 58);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 58);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 58);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 58);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 58);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 58);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 58);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 58);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 58);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 58);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 58);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 58);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 58);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 58);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 58);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 58);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 58);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 58);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 58);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 58);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 58);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 58);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 58);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 58);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 58);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 58);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 58);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 58);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 58);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 58);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 58);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 58);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 58);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 58);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang58_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 58);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang59() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 59);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 59);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 59);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 59);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 59);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 59);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 59);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 59);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 59);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 59);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 59);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 59);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 59);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 59);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 59);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 59);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 59);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 59);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 59);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 59);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 59);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 59);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 59);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 59);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 59);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 59);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 59);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 59);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 59);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 59);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 59);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 59);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 59);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 59);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 59);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 59);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 59);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 59);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 59);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 59);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 59);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 59);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 59);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 59);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 59);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 59);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 59);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 59);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 59);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 59);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 59);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 59);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 59);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 59);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang59_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 59);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  Future<void> hamKhoiTaoToaDoChiTietHang60() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 60);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 60);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 60);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 60);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 60);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 60);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 60);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 60);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 60);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 60);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 60);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 60);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 60);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 60);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 60);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 60);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 60);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 60);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 60);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 60);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 60);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 60);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 60);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 60);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 60);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 60);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 60);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 60);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 60);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 60);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 60);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 60);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 60);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 60);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 60);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 60);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 60);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 60);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 60);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 60);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 60);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 60);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 60);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 60);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 60);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 60);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 60);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 60);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 60);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 60);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 60);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 60);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 60);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 60);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang60_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 60);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }
}
