import 'package:pkg_dinh_nghia_ss020/dinh_nghia_thanh_phan_define.dart';
/// -----
/// TODO:
/// -----
class DiemToaDoChiTietPhamViDenHang100 {
  List<DiemToaDoCoBan> danhSachToaDo = [];

  Future<void> onInitList() async {
    await hamKhoiTaoToaDoChiTietHang91();
    await hamKhoiTaoToaDoChiTietHang92();
    await hamKhoiTaoToaDoChiTietHang93();
    await hamKhoiTaoToaDoChiTietHang94();
    await hamKhoiTaoToaDoChiTietHang95();
    await hamKhoiTaoToaDoChiTietHang96();
    await hamKhoiTaoToaDoChiTietHang97();
    await hamKhoiTaoToaDoChiTietHang98();
    await hamKhoiTaoToaDoChiTietHang99();
    await hamKhoiTaoToaDoChiTietHang100();
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang91() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 91);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 91);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 91);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 91);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 91);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 91);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 91);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 91);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 91);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 91);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 91);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 91);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 91);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 91);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 91);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 91);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 91);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 91);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 91);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 91);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 91);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 91);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 91);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 91);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 91);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 91);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 91);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 91);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 91);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 91);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 91);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 91);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 91);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 91);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 91);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 91);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 91);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 91);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 91);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 91);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 91);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 91);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 91);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 91);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 91);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 91);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 91);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 91);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 91);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 91);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 91);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 91);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 91);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 91);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang91_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 91);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang92() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 92);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 92);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 92);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 92);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 92);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 92);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 92);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 92);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 92);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 92);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 92);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 92);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 92);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 92);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 92);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 92);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 92);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 92);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 92);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 92);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 92);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 92);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 92);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 92);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 92);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 92);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 92);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 92);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 92);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 92);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 92);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 92);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 92);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 92);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 92);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 92);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 92);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 92);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 92);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 92);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 92);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 92);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 92);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 92);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 92);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 92);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 92);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 92);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 92);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 92);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 92);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 92);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 92);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 92);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang92_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 92);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang93() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 93);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 93);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 93);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 93);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 93);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 93);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 93);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 93);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 93);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 93);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 93);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 93);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 93);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 93);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 93);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 93);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 93);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 93);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 93);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 93);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 93);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 93);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 93);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 93);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 93);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 93);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 93);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 93);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 93);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 93);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 93);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 93);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 93);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 93);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 93);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 93);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 93);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 93);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 93);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 93);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 93);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 93);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 93);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 93);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 93);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 93);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 93);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 93);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 93);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 93);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 93);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 93);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 93);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 93);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang93_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 93);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang94() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 94);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 94);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 94);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 94);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 94);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 94);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 94);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 94);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 94);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 94);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 94);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 94);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 94);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 94);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 94);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 94);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 94);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 94);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 94);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 94);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 94);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 94);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 94);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 94);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 94);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 94);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 94);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 94);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 94);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 94);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 94);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 94);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 94);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 94);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 94);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 94);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 94);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 94);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 94);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 94);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 94);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 94);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 94);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 94);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 94);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 94);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 94);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 94);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 94);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 94);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 94);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 94);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 94);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 94);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang94_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 94);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang95() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 95);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 95);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 95);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 95);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 95);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 95);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 95);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 95);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 95);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 95);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 95);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 95);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 95);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 95);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 95);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 95);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 95);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 95);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 95);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 95);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 95);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 95);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 95);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 95);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 95);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 95);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 95);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 95);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 95);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 95);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 95);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 95);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 95);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 95);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 95);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 95);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 95);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 95);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 95);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 95);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 95);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 95);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 95);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 95);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 95);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 95);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 95);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 95);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 95);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 95);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 95);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 95);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 95);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 95);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang95_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 95);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang96() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 96);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 96);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 96);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 96);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 96);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 96);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 96);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 96);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 96);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 96);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 96);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 96);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 96);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 96);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 96);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 96);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 96);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 96);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 96);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 96);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 96);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 96);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 96);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 96);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 96);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 96);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 96);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 96);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 96);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 96);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 96);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 96);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 96);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 96);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 96);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 96);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 96);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 96);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 96);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 96);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 96);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 96);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 96);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 96);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 96);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 96);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 96);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 96);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 96);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 96);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 96);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 96);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 96);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 96);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang96_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 96);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang97() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 97);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 97);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 97);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 97);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 97);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 97);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 97);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 97);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 97);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 97);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 97);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 97);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 97);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 97);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 97);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 97);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 97);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 97);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 97);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 97);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 97);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 97);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 97);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 97);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 97);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 97);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 97);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 97);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 97);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 97);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 97);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 97);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 97);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 97);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 97);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 97);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 97);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 97);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 97);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 97);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 97);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 97);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 97);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 97);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 97);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 97);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 97);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 97);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 97);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 97);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 97);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 97);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 97);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 97);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang97_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 97);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang98() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 98);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 98);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 98);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 98);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 98);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 98);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 98);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 98);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 98);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 98);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 98);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 98);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 98);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 98);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 98);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 98);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 98);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 98);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 98);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 98);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 98);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 98);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 98);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 98);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 98);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 98);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 98);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 98);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 98);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 98);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 98);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 98);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 98);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 98);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 98);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 98);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 98);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 98);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 98);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 98);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 98);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 98);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 98);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 98);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 98);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 98);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 98);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 98);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 98);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 98);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 98);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 98);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 98);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 98);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang98_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 98);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang99() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 99);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 99);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 99);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 99);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 99);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 99);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 99);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 99);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 99);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 99);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 99);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 99);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 99);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 99);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 99);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 99);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 99);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 99);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 99);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 99);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 99);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 99);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 99);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 99);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 99);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 99);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 99);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 99);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 99);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 99);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 99);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 99);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 99);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 99);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 99);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 99);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 99);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 99);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 99);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 99);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 99);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 99);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 99);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 99);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 99);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 99);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 99);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 99);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 99);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 99);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 99);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 99);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 99);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 99);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang99_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 99);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  Future<void> hamKhoiTaoToaDoChiTietHang100() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 100);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 100);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 100);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 100);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 100);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 100);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 100);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 100);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 100);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 100);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 100);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 100);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 100);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 100);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 100);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 100);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 100);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 100);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 100);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 100);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 100);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 100);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 100);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 100);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 100);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 100);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 100);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 100);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 100);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 100);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 100);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 100);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 100);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 100);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 100);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 100);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 100);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 100);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 100);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 100);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 100);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 100);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 100);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 100);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 100);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 100);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 100);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 100);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 100);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 100);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 100);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 100);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 100);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 100);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang100_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 100);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }
}
