import 'package:pkg_dinh_nghia_ss020/dinh_nghia_thanh_phan_define.dart';
/// -----
/// TODO:
/// -----
class DiemToaDoChiTietPhamViDenHang70 {
  List<DiemToaDoCoBan> danhSachToaDo = [];

  Future<void> onInitList() async {
    await hamKhoiTaoToaDoChiTietHang61();
    await hamKhoiTaoToaDoChiTietHang62();
    await hamKhoiTaoToaDoChiTietHang63();
    await hamKhoiTaoToaDoChiTietHang64();
    await hamKhoiTaoToaDoChiTietHang65();
    await hamKhoiTaoToaDoChiTietHang66();
    await hamKhoiTaoToaDoChiTietHang67();
    await hamKhoiTaoToaDoChiTietHang68();
    await hamKhoiTaoToaDoChiTietHang69();
    await hamKhoiTaoToaDoChiTietHang70();
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang61() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 61);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 61);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 61);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 61);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 61);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 61);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 61);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 61);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 61);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 61);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 61);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 61);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 61);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 61);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 61);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 61);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 61);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 61);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 61);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 61);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 61);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 61);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 61);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 61);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 61);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 61);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 61);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 61);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 61);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 61);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 61);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 61);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 61);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 61);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 61);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 61);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 61);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 61);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 61);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 61);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 61);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 61);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 61);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 61);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 61);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 61);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 61);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 61);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 61);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 61);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 61);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 61);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 61);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 61);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang61_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 61);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang62() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 62);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 62);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 62);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 62);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 62);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 62);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 62);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 62);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 62);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 62);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 62);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 62);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 62);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 62);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 62);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 62);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 62);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 62);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 62);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 62);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 62);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 62);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 62);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 62);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 62);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 62);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 62);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 62);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 62);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 62);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 62);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 62);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 62);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 62);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 62);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 62);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 62);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 62);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 62);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 62);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 62);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 62);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 62);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 62);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 62);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 62);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 62);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 62);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 62);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 62);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 62);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 62);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 62);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 62);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang62_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 62);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang63() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 63);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 63);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 63);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 63);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 63);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 63);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 63);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 63);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 63);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 63);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 63);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 63);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 63);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 63);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 63);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 63);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 63);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 63);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 63);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 63);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 63);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 63);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 63);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 63);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 63);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 63);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 63);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 63);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 63);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 63);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 63);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 63);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 63);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 63);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 63);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 63);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 63);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 63);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 63);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 63);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 63);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 63);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 63);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 63);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 63);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 63);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 63);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 63);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 63);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 63);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 63);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 63);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 63);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 63);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang63_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 63);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang64() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 64);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 64);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 64);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 64);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 64);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 64);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 64);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 64);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 64);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 64);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 64);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 64);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 64);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 64);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 64);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 64);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 64);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 64);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 64);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 64);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 64);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 64);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 64);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 64);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 64);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 64);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 64);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 64);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 64);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 64);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 64);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 64);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 64);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 64);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 64);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 64);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 64);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 64);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 64);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 64);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 64);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 64);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 64);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 64);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 64);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 64);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 64);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 64);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 64);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 64);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 64);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 64);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 64);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 64);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang64_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 64);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang65() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 65);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 65);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 65);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 65);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 65);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 65);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 65);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 65);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 65);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 65);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 65);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 65);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 65);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 65);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 65);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 65);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 65);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 65);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 65);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 65);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 65);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 65);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 65);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 65);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 65);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 65);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 65);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 65);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 65);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 65);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 65);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 65);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 65);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 65);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 65);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 65);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 65);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 65);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 65);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 65);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 65);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 65);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 65);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 65);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 65);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 65);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 65);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 65);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 65);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 65);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 65);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 65);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 65);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 65);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang65_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 65);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang66() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 66);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 66);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 66);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 66);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 66);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 66);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 66);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 66);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 66);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 66);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 66);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 66);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 66);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 66);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 66);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 66);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 66);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 66);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 66);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 66);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 66);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 66);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 66);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 66);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 66);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 66);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 66);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 66);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 66);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 66);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 66);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 66);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 66);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 66);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 66);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 66);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 66);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 66);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 66);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 66);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 66);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 66);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 66);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 66);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 66);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 66);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 66);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 66);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 66);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 66);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 66);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 66);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 66);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 66);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang66_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 66);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang67() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 67);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 67);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 67);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 67);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 67);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 67);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 67);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 67);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 67);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 67);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 67);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 67);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 67);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 67);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 67);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 67);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 67);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 67);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 67);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 67);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 67);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 67);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 67);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 67);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 67);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 67);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 67);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 67);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 67);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 67);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 67);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 67);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 67);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 67);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 67);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 67);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 67);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 67);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 67);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 67);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 67);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 67);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 67);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 67);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 67);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 67);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 67);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 67);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 67);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 67);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 67);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 67);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 67);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 67);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang67_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 67);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang68() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 68);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 68);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 68);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 68);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 68);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 68);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 68);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 68);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 68);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 68);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 68);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 68);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 68);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 68);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 68);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 68);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 68);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 68);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 68);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 68);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 68);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 68);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 68);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 68);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 68);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 68);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 68);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 68);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 68);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 68);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 68);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 68);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 68);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 68);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 68);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 68);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 68);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 68);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 68);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 68);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 68);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 68);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 68);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 68);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 68);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 68);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 68);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 68);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 68);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 68);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 68);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 68);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 68);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 68);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang68_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 68);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang69() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 69);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 69);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 69);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 69);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 69);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 69);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 69);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 69);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 69);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 69);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 69);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 69);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 69);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 69);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 69);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 69);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 69);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 69);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 69);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 69);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 69);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 69);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 69);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 69);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 69);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 69);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 69);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 69);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 69);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 69);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 69);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 69);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 69);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 69);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 69);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 69);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 69);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 69);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 69);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 69);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 69);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 69);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 69);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 69);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 69);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 69);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 69);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 69);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 69);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 69);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 69);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 69);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 69);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 69);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang69_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 69);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  Future<void> hamKhoiTaoToaDoChiTietHang70() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 70);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 70);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 70);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 70);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 70);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 70);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 70);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 70);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 70);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 70);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 70);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 70);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 70);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 70);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 70);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 70);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 70);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 70);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 70);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 70);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 70);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 70);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 70);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 70);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 70);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 70);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 70);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 70);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 70);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 70);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 70);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 70);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 70);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 70);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 70);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 70);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 70);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 70);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 70);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 70);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 70);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 70);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 70);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 70);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 70);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 70);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 70);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 70);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 70);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 70);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 70);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 70);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 70);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 70);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang70_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 70);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }
}
