import 'package:pkg_dinh_nghia_ss020/dinh_nghia_thanh_phan_define.dart';
/// -----
/// TODO:
/// -----
class DiemToaDoChiTietPhamViDenHang30 {
  List<DiemToaDoCoBan> danhSachToaDo = [];

  Future<void> onInitList() async {
    await hamKhoiTaoToaDoChiTietHang21();
    await hamKhoiTaoToaDoChiTietHang22();
    await hamKhoiTaoToaDoChiTietHang23();
    await hamKhoiTaoToaDoChiTietHang24();
    await hamKhoiTaoToaDoChiTietHang25();
    await hamKhoiTaoToaDoChiTietHang26();
    await hamKhoiTaoToaDoChiTietHang27();
    await hamKhoiTaoToaDoChiTietHang28();
    await hamKhoiTaoToaDoChiTietHang29();
    await hamKhoiTaoToaDoChiTietHang30();
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang21() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 21);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 21);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 21);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 21);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 21);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 21);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 21);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 21);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 21);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 21);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 21);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 21);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 21);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 21);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 21);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 21);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 21);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 21);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 21);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 21);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 21);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 21);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 21);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 21);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 21);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 21);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 21);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 21);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 21);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 21);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 21);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 21);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 21);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 21);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 21);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 21);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 21);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 21);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 21);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 21);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 21);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 21);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 21);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 21);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 21);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 21);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 21);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 21);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 21);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 21);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 21);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 21);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 21);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 21);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang21_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 21);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang22() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 22);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 22);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 22);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 22);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 22);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 22);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 22);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 22);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 22);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 22);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 22);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 22);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 22);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 22);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 22);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 22);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 22);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 22);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 22);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 22);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 22);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 22);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 22);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 22);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 22);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 22);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 22);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 22);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 22);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 22);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 22);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 22);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 22);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 22);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 22);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 22);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 22);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 22);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 22);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 22);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 22);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 22);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 22);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 22);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 22);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 22);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 22);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 22);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 22);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 22);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 22);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 22);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 22);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 22);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang22_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 22);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang23() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 23);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 23);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 23);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 23);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 23);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 23);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 23);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 23);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 23);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 23);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 23);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 23);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 23);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 23);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 23);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 23);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 23);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 23);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 23);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 23);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 23);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 23);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 23);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 23);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 23);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 23);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 23);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 23);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 23);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 23);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 23);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 23);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 23);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 23);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 23);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 23);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 23);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 23);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 23);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 23);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 23);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 23);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 23);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 23);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 23);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 23);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 23);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 23);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 23);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 23);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 23);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 23);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 23);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 23);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang23_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 23);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang24() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 24);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 24);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 24);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 24);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 24);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 24);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 24);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 24);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 24);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 24);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 24);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 24);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 24);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 24);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 24);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 24);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 24);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 24);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 24);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 24);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 24);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 24);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 24);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 24);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 24);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 24);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 24);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 24);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 24);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 24);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 24);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 24);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 24);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 24);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 24);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 24);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 24);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 24);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 24);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 24);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 24);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 24);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 24);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 24);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 24);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 24);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 24);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 24);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 24);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 24);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 24);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 24);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 24);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 24);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang24_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 24);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang25() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 25);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 25);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 25);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 25);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 25);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 25);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 25);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 25);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 25);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 25);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 25);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 25);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 25);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 25);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 25);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 25);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 25);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 25);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 25);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 25);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 25);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 25);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 25);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 25);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 25);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 25);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 25);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 25);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 25);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 25);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 25);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 25);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 25);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 25);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 25);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 25);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 25);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 25);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 25);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 25);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 25);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 25);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 25);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 25);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 25);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 25);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 25);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 25);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 25);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 25);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 25);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 25);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 25);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 25);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang25_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 25);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang26() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 26);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 26);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 26);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 26);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 26);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 26);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 26);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 26);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 26);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 26);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 26);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 26);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 26);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 26);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 26);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 26);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 26);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 26);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 26);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 26);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 26);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 26);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 26);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 26);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 26);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 26);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 26);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 26);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 26);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 26);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 26);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 26);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 26);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 26);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 26);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 26);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 26);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 26);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 26);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 26);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 26);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 26);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 26);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 26);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 26);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 26);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 26);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 26);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 26);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 26);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 26);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 26);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 26);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 26);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang26_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 26);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang27() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 27);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 27);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 27);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 27);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 27);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 27);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 27);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 27);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 27);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 27);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 27);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 27);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 27);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 27);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 27);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 27);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 27);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 27);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 27);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 27);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 27);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 27);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 27);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 27);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 27);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 27);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 27);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 27);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 27);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 27);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 27);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 27);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 27);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 27);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 27);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 27);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 27);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 27);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 27);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 27);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 27);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 27);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 27);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 27);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 27);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 27);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 27);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 27);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 27);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 27);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 27);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 27);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 27);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 27);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang27_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 27);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang28() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 28);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 28);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 28);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 28);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 28);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 28);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 28);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 28);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 28);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 28);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 28);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 28);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 28);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 28);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 28);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 28);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 28);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 28);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 28);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 28);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 28);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 28);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 28);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 28);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 28);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 28);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 28);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 28);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 28);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 28);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 28);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 28);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 28);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 28);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 28);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 28);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 28);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 28);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 28);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 28);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 28);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 28);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 28);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 28);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 28);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 28);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 28);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 28);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 28);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 28);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 28);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 28);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 28);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 28);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang28_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 28);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang29() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 29);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 29);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 29);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 29);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 29);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 29);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 29);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 29);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 29);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 29);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 29);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 29);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 29);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 29);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 29);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 29);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 29);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 29);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 29);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 29);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 29);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 29);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 29);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 29);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 29);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 29);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 29);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 29);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 29);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 29);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 29);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 29);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 29);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 29);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 29);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 29);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 29);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 29);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 29);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 29);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 29);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 29);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 29);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 29);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 29);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 29);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 29);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 29);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 29);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 29);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 29);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 29);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 29);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 29);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang29_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 29);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  Future<void> hamKhoiTaoToaDoChiTietHang30() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 30);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 30);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 30);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 30);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 30);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 30);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 30);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 30);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 30);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 30);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 30);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 30);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 30);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 30);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 30);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 30);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 30);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 30);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 30);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 30);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 30);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 30);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 30);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 30);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 30);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 30);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 30);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 30);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 30);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 30);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 30);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 30);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 30);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 30);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 30);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 30);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 30);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 30);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 30);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 30);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 30);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 30);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 30);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 30);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 30);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 30);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 30);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 30);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 30);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 30);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 30);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 30);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 30);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 30);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang30_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 30);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }
}
