import 'package:pkg_dinh_nghia_ss020/dinh_nghia_thanh_phan_define.dart';
/// -----
/// TODO:
/// -----
class DiemToaDoChiTietPhamViDenHang40 {
  List<DiemToaDoCoBan> danhSachToaDo = [];

  Future<void> onInitList() async {
    await hamKhoiTaoToaDoChiTietHang31();
    await hamKhoiTaoToaDoChiTietHang32();
    await hamKhoiTaoToaDoChiTietHang33();
    await hamKhoiTaoToaDoChiTietHang34();
    await hamKhoiTaoToaDoChiTietHang35();
    await hamKhoiTaoToaDoChiTietHang36();
    await hamKhoiTaoToaDoChiTietHang37();
    await hamKhoiTaoToaDoChiTietHang38();
    await hamKhoiTaoToaDoChiTietHang39();
    await hamKhoiTaoToaDoChiTietHang40();
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang31() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 31);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 31);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 31);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 31);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 31);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 31);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 31);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 31);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 31);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 31);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 31);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 31);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 31);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 31);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 31);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 31);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 31);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 31);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 31);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 31);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 31);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 31);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 31);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 31);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 31);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 31);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 31);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 31);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 31);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 31);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 31);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 31);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 31);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 31);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 31);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 31);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 31);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 31);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 31);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 31);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 31);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 31);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 31);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 31);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 31);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 31);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 31);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 31);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 31);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 31);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 31);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 31);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 31);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 31);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang31_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 31);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang32() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 32);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 32);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 32);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 32);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 32);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 32);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 32);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 32);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 32);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 32);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 32);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 32);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 32);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 32);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 32);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 32);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 32);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 32);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 32);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 32);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 32);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 32);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 32);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 32);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 32);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 32);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 32);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 32);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 32);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 32);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 32);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 32);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 32);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 32);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 32);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 32);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 32);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 32);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 32);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 32);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 32);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 32);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 32);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 32);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 32);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 32);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 32);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 32);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 32);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 32);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 32);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 32);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 32);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 32);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang32_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 32);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang33() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 33);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 33);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 33);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 33);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 33);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 33);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 33);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 33);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 33);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 33);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 33);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 33);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 33);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 33);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 33);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 33);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 33);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 33);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 33);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 33);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 33);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 33);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 33);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 33);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 33);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 33);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 33);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 33);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 33);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 33);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 33);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 33);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 33);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 33);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 33);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 33);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 33);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 33);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 33);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 33);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 33);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 33);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 33);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 33);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 33);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 33);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 33);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 33);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 33);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 33);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 33);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 33);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 33);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 33);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang33_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 33);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang34() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 34);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 34);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 34);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 34);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 34);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 34);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 34);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 34);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 34);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 34);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 34);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 34);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 34);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 34);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 34);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 34);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 34);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 34);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 34);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 34);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 34);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 34);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 34);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 34);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 34);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 34);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 34);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 34);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 34);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 34);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 34);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 34);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 34);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 34);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 34);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 34);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 34);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 34);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 34);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 34);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 34);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 34);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 34);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 34);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 34);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 34);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 34);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 34);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 34);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 34);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 34);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 34);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 34);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 34);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang34_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 34);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang35() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 35);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 35);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 35);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 35);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 35);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 35);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 35);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 35);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 35);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 35);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 35);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 35);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 35);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 35);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 35);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 35);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 35);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 35);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 35);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 35);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 35);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 35);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 35);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 35);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 35);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 35);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 35);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 35);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 35);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 35);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 35);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 35);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 35);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 35);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 35);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 35);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 35);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 35);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 35);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 35);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 35);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 35);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 35);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 35);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 35);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 35);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 35);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 35);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 35);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 35);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 35);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 35);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 35);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 35);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang35_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 35);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang36() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 36);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 36);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 36);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 36);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 36);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 36);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 36);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 36);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 36);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 36);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 36);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 36);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 36);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 36);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 36);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 36);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 36);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 36);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 36);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 36);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 36);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 36);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 36);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 36);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 36);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 36);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 36);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 36);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 36);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 36);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 36);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 36);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 36);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 36);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 36);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 36);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 36);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 36);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 36);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 36);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 36);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 36);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 36);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 36);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 36);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 36);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 36);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 36);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 36);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 36);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 36);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 36);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 36);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 36);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang36_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 36);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang37() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 37);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 37);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 37);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 37);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 37);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 37);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 37);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 37);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 37);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 37);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 37);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 37);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 37);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 37);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 37);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 37);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 37);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 37);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 37);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 37);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 37);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 37);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 37);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 37);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 37);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 37);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 37);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 37);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 37);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 37);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 37);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 37);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 37);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 37);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 37);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 37);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 37);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 37);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 37);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 37);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 37);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 37);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 37);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 37);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 37);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 37);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 37);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 37);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 37);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 37);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 37);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 37);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 37);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 37);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang37_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 37);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang38() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 38);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 38);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 38);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 38);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 38);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 38);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 38);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 38);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 38);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 38);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 38);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 38);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 38);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 38);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 38);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 38);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 38);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 38);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 38);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 38);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 38);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 38);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 38);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 38);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 38);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 38);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 38);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 38);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 38);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 38);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 38);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 38);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 38);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 38);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 38);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 38);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 38);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 38);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 38);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 38);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 38);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 38);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 38);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 38);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 38);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 38);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 38);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 38);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 38);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 38);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 38);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 38);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 38);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 38);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang38_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 38);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang39() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 39);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 39);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 39);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 39);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 39);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 39);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 39);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 39);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 39);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 39);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 39);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 39);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 39);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 39);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 39);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 39);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 39);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 39);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 39);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 39);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 39);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 39);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 39);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 39);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 39);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 39);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 39);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 39);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 39);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 39);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 39);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 39);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 39);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 39);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 39);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 39);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 39);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 39);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 39);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 39);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 39);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 39);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 39);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 39);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 39);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 39);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 39);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 39);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 39);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 39);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 39);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 39);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 39);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 39);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang39_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 39);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  Future<void> hamKhoiTaoToaDoChiTietHang40() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 40);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 40);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 40);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 40);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 40);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 40);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 40);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 40);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 40);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 40);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 40);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 40);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 40);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 40);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 40);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 40);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 40);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 40);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 40);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 40);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 40);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 40);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 40);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 40);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 40);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 40);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 40);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 40);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 40);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 40);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 40);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 40);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 40);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 40);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 40);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 40);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 40);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 40);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 40);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 40);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 40);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 40);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 40);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 40);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 40);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 40);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 40);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 40);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 40);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 40);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 40);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 40);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 40);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 40);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang40_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 40);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }
}
