import 'package:pkg_dinh_nghia_ss020/dinh_nghia_thanh_phan_define.dart';
/// -----
/// TODO:
/// -----
class DiemToaDoChiTietPhamViDenHang20 {
  List<DiemToaDoCoBan> danhSachToaDo = [];

  Future<void> onInitList() async {
    await hamKhoiTaoToaDoChiTietHang11();
    await hamKhoiTaoToaDoChiTietHang12();
    await hamKhoiTaoToaDoChiTietHang13();
    await hamKhoiTaoToaDoChiTietHang14();
    await hamKhoiTaoToaDoChiTietHang15();
    await hamKhoiTaoToaDoChiTietHang16();
    await hamKhoiTaoToaDoChiTietHang17();
    await hamKhoiTaoToaDoChiTietHang18();
    await hamKhoiTaoToaDoChiTietHang19();
    await hamKhoiTaoToaDoChiTietHang20();
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang11() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 11);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 11);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 11);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 11);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 11);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 11);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 11);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 11);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 11);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 11);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 11);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 11);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 11);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 11);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 11);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 11);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 11);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 11);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 11);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 11);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 11);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 11);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 11);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 11);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 11);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 11);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 11);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 11);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 11);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 11);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 11);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 11);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 11);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 11);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 11);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 11);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 11);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 11);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 11);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 11);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 11);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 11);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 11);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 11);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 11);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 11);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 11);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 11);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 11);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 11);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 11);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 11);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 11);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 11);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang11_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 11);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang12() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 12);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 12);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 12);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 12);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 12);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 12);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 12);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 12);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 12);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 12);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 12);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 12);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 12);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 12);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 12);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 12);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 12);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 12);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 12);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 12);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 12);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 12);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 12);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 12);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 12);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 12);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 12);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 12);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 12);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 12);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 12);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 12);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 12);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 12);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 12);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 12);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 12);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 12);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 12);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 12);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 12);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 12);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 12);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 12);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 12);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 12);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 12);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 12);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 12);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 12);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 12);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 12);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 12);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 12);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang12_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 12);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang13() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 13);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 13);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 13);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 13);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 13);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 13);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 13);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 13);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 13);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 13);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 13);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 13);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 13);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 13);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 13);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 13);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 13);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 13);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 13);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 13);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 13);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 13);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 13);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 13);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 13);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 13);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 13);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 13);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 13);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 13);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 13);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 13);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 13);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 13);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 13);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 13);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 13);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 13);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 13);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 13);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 13);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 13);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 13);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 13);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 13);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 13);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 13);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 13);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 13);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 13);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 13);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 13);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 13);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 13);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang13_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 13);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang14() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 14);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 14);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 14);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 14);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 14);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 14);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 14);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 14);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 14);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 14);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 14);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 14);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 14);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 14);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 14);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 14);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 14);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 14);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 14);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 14);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 14);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 14);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 14);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 14);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 14);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 14);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 14);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 14);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 14);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 14);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 14);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 14);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 14);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 14);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 14);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 14);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 14);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 14);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 14);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 14);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 14);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 14);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 14);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 14);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 14);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 14);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 14);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 14);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 14);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 14);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 14);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 14);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 14);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 14);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang14_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 14);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang15() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 15);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 15);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 15);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 15);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 15);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 15);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 15);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 15);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 15);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 15);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 15);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 15);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 15);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 15);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 15);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 15);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 15);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 15);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 15);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 15);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 15);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 15);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 15);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 15);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 15);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 15);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 15);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 15);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 15);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 15);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 15);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 15);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 15);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 15);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 15);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 15);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 15);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 15);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 15);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 15);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 15);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 15);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 15);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 15);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 15);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 15);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 15);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 15);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 15);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 15);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 15);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 15);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 15);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 15);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang15_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 15);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang16() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 16);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 16);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 16);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 16);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 16);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 16);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 16);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 16);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 16);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 16);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 16);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 16);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 16);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 16);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 16);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 16);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 16);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 16);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 16);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 16);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 16);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 16);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 16);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 16);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 16);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 16);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 16);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 16);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 16);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 16);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 16);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 16);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 16);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 16);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 16);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 16);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 16);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 16);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 16);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 16);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 16);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 16);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 16);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 16);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 16);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 16);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 16);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 16);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 16);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 16);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 16);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 16);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 16);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 16);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang16_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 16);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang17() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 17);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 17);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 17);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 17);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 17);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 17);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 17);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 17);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 17);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 17);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 17);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 17);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 17);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 17);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 17);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 17);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 17);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 17);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 17);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 17);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 17);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 17);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 17);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 17);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 17);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 17);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 17);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 17);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 17);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 17);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 17);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 17);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 17);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 17);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 17);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 17);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 17);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 17);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 17);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 17);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 17);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 17);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 17);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 17);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 17);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 17);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 17);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 17);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 17);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 17);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 17);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 17);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 17);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 17);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang17_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 17);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang18() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 18);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 18);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 18);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 18);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 18);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 18);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 18);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 18);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 18);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 18);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 18);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 18);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 18);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 18);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 18);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 18);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 18);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 18);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 18);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 18);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 18);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 18);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 18);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 18);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 18);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 18);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 18);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 18);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 18);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 18);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 18);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 18);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 18);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 18);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 18);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 18);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 18);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 18);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 18);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 18);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 18);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 18);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 18);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 18);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 18);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 18);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 18);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 18);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 18);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 18);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 18);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 18);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 18);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 18);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang18_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 18);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang19() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 19);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 19);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 19);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 19);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 19);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 19);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 19);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 19);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 19);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 19);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 19);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 19);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 19);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 19);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 19);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 19);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 19);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 19);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 19);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 19);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 19);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 19);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 19);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 19);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 19);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 19);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 19);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 19);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 19);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 19);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 19);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 19);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 19);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 19);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 19);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 19);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 19);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 19);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 19);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 19);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 19);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 19);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 19);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 19);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 19);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 19);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 19);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 19);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 19);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 19);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 19);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 19);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 19);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 19);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang19_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 19);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  Future<void> hamKhoiTaoToaDoChiTietHang20() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 20);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 20);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 20);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 20);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 20);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 20);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 20);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 20);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 20);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 20);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 20);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 20);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 20);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 20);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 20);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 20);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 20);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 20);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 20);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 20);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 20);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 20);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 20);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 20);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 20);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 20);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 20);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 20);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 20);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 20);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 20);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 20);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 20);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 20);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 20);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 20);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 20);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 20);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 20);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 20);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 20);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 20);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 20);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 20);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 20);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 20);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 20);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 20);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 20);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 20);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 20);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 20);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 20);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 20);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang20_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 20);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }
}
