name: pkg_man_hinh_ss00024
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pkg_dinh_nghia_ss020:
    path: ../pkg_dinh_nghia_ss020
  pkg_dinh_nghia_ss022:
    path: ../pkg_dinh_nghia_ss022
  pkg_dinh_nghia_ss028:
    path: ../pkg_dinh_nghia_ss028
  pkg_dinh_nghia_ss050:
    path: ../pkg_dinh_nghia_ss050

  pkg_dinh_nghia_ss028020:
    path: ../pkg_dinh_nghia_ss028020

  pkg_dinh_nghia_ss028022:
    path: ../pkg_dinh_nghia_ss028022

  pkg_dinh_nghia_dv_ss0030:
    path: ../pkg_dinh_nghia_dv_ss0030

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
   assets:
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00E03_SS01]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def20_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_popup_cua_hang_CDC00E03SS01.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def20_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_the_cua_hang_CDC00E03SS01.png
     #
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00E03_SS02]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def20_6/08_SubDefs/Def22_8/06_ImgSrcs/hinh_popup_cua_hang_CDC00E03SS02.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def20_6/08_SubDefs/Def22_8/06_ImgSrcs/hinh_the_cua_hang_CDC00E03SS02.png
     #
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00E03_SS03]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def20_6/08_SubDefs/Def24_8/06_ImgSrcs/hinh_popup_cua_hang_CDC00E03SS03.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def20_6/08_SubDefs/Def24_8/06_ImgSrcs/hinh_the_cua_hang_CDC00E03SS03.png
     #
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00D04_SS01]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def22_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_popup_cua_hang_CDC00D04SS01.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def22_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_the_cua_hang_CDC00D04SS01.png
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00C05_SS01]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def24_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_popup_cua_hang_CDC00C05SS01.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def24_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_the_cua_hang_CDC00C05SS01.png
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00B06_SS01]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def26_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_popup_cua_hang_CDC00B06SS01.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def26_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_the_cua_hang_CDC00B06SS01.png
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00A07_SS01]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def28_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_popup_cua_hang_CDC00A07SS01.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def28_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_the_cua_hang_CDC00A07SS01.png
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00S08_SS01]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def30_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_popup_cua_hang_CDC00S08SS01.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def30_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_the_cua_hang_CDC00S08SS01.png
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_0SS09_SS01]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def32_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_popup_cua_hang_CDC0SS09SS01.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def32_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_the_cua_hang_CDC0SS09SS01.png
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_0SS09_SS02]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def32_6/08_SubDefs/Def22_8/06_ImgSrcs/hinh_popup_cua_hang_CDC0SS09SS02.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def32_6/08_SubDefs/Def22_8/06_ImgSrcs/hinh_the_cua_hang_CDC0SS09SS02.png
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_0SS09_SS03]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def32_6/08_SubDefs/Def24_8/06_ImgSrcs/hinh_popup_cua_hang_CDC0SS09SS03.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def32_6/08_SubDefs/Def24_8/06_ImgSrcs/hinh_the_cua_hang_CDC0SS09SS03.png
     #
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS01]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def34_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_popup_cua_hang_CDCSSS10SS01.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def34_6/08_SubDefs/Def20_8/06_ImgSrcs/hinh_the_cua_hang_CDCSSS10SS01.png
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS02]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def34_6/08_SubDefs/Def22_8/06_ImgSrcs/hinh_popup_cua_hang_CDCSSS10SS02.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def34_6/08_SubDefs/Def22_8/06_ImgSrcs/hinh_the_cua_hang_CDCSSS10SS02.png
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS03]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def34_6/08_SubDefs/Def24_8/06_ImgSrcs/hinh_popup_cua_hang_CDCSSS10SS03.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def34_6/08_SubDefs/Def24_8/06_ImgSrcs/hinh_the_cua_hang_CDCSSS10SS03.png
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS04]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def34_6/08_SubDefs/Def26_8/06_ImgSrcs/hinh_popup_cua_hang_CDCSSS10SS04.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def34_6/08_SubDefs/Def26_8/06_ImgSrcs/hinh_the_cua_hang_CDCSSS10SS04.png
     # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS05]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def34_6/08_SubDefs/Def28_8/06_ImgSrcs/hinh_popup_cua_hang_CDCSSS10SS05.png
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def26_4/08_SubDefs/Def34_6/08_SubDefs/Def28_8/06_ImgSrcs/hinh_the_cua_hang_CDCSSS10SS05.png
     #
     #
     #
     #
     #
     #
     #
     #
     #
     #
     #
     #
     #
     #
     #
     #
     #
     #
     #
     #
     #
     # _____
     # _____[Nut_Bam_Xem_Thong_Tin_Chien_Dau_Co]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def24_4/08_SubDefs/Def22_6/08_SubDefs/Def20_8/06_ImgSrcs/nut_bam_xem_thong_tin_chien_dau_co.png
     # _____
     # _____[Nut_Bam_Trao_Doi_Mua_Chien_Dau_Co_Phuong_Thuc_SS01]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def24_4/08_SubDefs/Def22_6/08_SubDefs/Def22_8/06_ImgSrcs/nut_bam_trao_doi_mua_chien_dau_co_phuong_thuc_ss01.png
     # _____
     # _____[Nut_Bam_Trao_Doi_Mua_Chien_Dau_Co_Phuong_Thuc_SS02]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def24_4/08_SubDefs/Def22_6/08_SubDefs/Def24_8/06_ImgSrcs/nut_bam_trao_doi_mua_chien_dau_co_phuong_thuc_ss02.png
     # _____
     # _____[Nut_Bam_Trao_Doi_Mua_Chien_Dau_Co_Phuong_Thuc_SS03]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def24_4/08_SubDefs/Def22_6/08_SubDefs/Def26_8/06_ImgSrcs/nut_bam_trao_doi_mua_chien_dau_co_phuong_thuc_ss03.png
     # _____
     # _____[Khung_Van_Ban_Thanh_Toan_So_Huu_Chien_Dau_Co]_____
     - lib/24_def0024/ADef22_0/08_SubDefs/Def20_2/08_SubDefs/Def22_4/08_SubDefs/Def24_6/06_ImgSrcs/hinh_van_ban_thanh_toan_so_huu_chien_dau_co.png
     # _____
     # _____
     # _____
     # _____
     # _____
     # _____
     # _____
     # _____
     # _____
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
