import 'package:pkg_dinh_nghia_ss020/dinh_nghia_thanh_phan_define.dart';
/// -----
/// TODO:
/// -----
class DiemToaDoChiTietPhamViDenHang80 {
  List<DiemToaDoCoBan> danhSachToaDo = [];

  Future<void> onInitList() async {
    await hamKhoiTaoToaDoChiTietHang71();
    await hamKhoiTaoToaDoChiTietHang72();
    await hamKhoiTaoToaDoChiTietHang73();
    await hamKhoiTaoToaDoChiTietHang74();
    await hamKhoiTaoToaDoChiTietHang75();
    await hamKhoiTaoToaDoChiTietHang76();
    await hamKhoiTaoToaDoChiTietHang77();
    await hamKhoiTaoToaDoChiTietHang78();
    await hamKhoiTaoToaDoChiTietHang79();
    await hamKhoiTaoToaDoChiTietHang80();
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang71() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 71);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 71);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 71);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 71);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 71);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 71);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 71);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 71);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 71);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 71);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 71);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 71);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 71);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 71);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 71);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 71);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 71);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 71);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 71);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 71);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 71);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 71);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 71);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 71);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 71);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 71);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 71);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 71);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 71);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 71);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 71);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 71);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 71);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 71);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 71);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 71);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 71);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 71);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 71);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 71);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 71);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 71);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 71);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 71);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 71);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 71);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 71);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 71);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 71);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 71);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 71);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 71);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 71);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 71);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang71_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 71);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang72() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 72);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 72);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 72);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 72);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 72);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 72);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 72);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 72);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 72);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 72);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 72);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 72);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 72);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 72);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 72);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 72);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 72);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 72);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 72);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 72);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 72);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 72);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 72);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 72);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 72);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 72);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 72);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 72);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 72);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 72);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 72);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 72);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 72);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 72);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 72);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 72);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 72);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 72);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 72);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 72);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 72);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 72);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 72);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 72);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 72);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 72);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 72);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 72);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 72);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 72);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 72);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 72);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 72);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 72);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang72_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 72);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang73() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 73);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 73);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 73);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 73);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 73);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 73);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 73);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 73);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 73);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 73);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 73);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 73);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 73);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 73);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 73);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 73);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 73);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 73);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 73);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 73);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 73);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 73);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 73);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 73);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 73);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 73);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 73);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 73);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 73);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 73);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 73);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 73);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 73);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 73);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 73);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 73);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 73);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 73);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 73);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 73);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 73);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 73);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 73);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 73);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 73);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 73);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 73);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 73);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 73);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 73);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 73);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 73);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 73);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 73);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang73_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 73);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang74() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 74);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 74);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 74);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 74);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 74);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 74);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 74);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 74);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 74);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 74);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 74);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 74);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 74);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 74);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 74);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 74);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 74);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 74);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 74);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 74);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 74);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 74);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 74);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 74);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 74);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 74);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 74);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 74);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 74);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 74);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 74);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 74);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 74);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 74);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 74);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 74);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 74);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 74);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 74);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 74);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 74);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 74);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 74);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 74);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 74);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 74);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 74);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 74);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 74);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 74);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 74);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 74);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 74);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 74);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang74_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 74);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang75() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 75);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 75);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 75);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 75);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 75);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 75);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 75);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 75);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 75);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 75);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 75);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 75);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 75);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 75);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 75);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 75);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 75);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 75);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 75);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 75);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 75);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 75);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 75);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 75);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 75);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 75);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 75);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 75);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 75);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 75);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 75);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 75);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 75);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 75);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 75);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 75);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 75);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 75);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 75);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 75);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 75);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 75);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 75);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 75);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 75);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 75);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 75);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 75);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 75);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 75);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 75);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 75);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 75);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 75);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang75_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 75);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang76() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 76);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 76);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 76);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 76);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 76);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 76);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 76);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 76);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 76);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 76);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 76);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 76);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 76);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 76);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 76);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 76);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 76);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 76);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 76);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 76);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 76);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 76);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 76);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 76);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 76);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 76);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 76);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 76);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 76);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 76);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 76);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 76);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 76);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 76);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 76);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 76);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 76);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 76);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 76);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 76);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 76);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 76);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 76);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 76);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 76);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 76);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 76);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 76);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 76);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 76);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 76);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 76);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 76);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 76);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang76_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 76);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang77() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 77);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 77);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 77);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 77);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 77);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 77);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 77);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 77);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 77);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 77);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 77);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 77);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 77);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 77);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 77);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 77);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 77);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 77);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 77);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 77);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 77);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 77);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 77);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 77);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 77);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 77);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 77);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 77);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 77);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 77);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 77);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 77);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 77);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 77);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 77);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 77);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 77);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 77);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 77);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 77);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 77);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 77);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 77);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 77);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 77);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 77);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 77);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 77);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 77);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 77);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 77);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 77);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 77);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 77);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang77_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 77);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang78() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 78);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 78);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 78);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 78);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 78);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 78);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 78);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 78);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 78);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 78);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 78);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 78);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 78);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 78);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 78);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 78);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 78);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 78);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 78);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 78);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 78);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 78);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 78);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 78);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 78);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 78);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 78);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 78);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 78);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 78);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 78);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 78);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 78);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 78);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 78);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 78);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 78);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 78);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 78);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 78);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 78);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 78);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 78);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 78);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 78);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 78);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 78);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 78);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 78);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 78);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 78);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 78);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 78);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 78);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang78_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 78);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang79() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 79);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 79);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 79);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 79);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 79);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 79);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 79);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 79);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 79);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 79);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 79);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 79);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 79);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 79);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 79);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 79);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 79);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 79);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 79);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 79);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 79);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 79);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 79);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 79);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 79);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 79);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 79);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 79);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 79);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 79);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 79);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 79);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 79);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 79);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 79);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 79);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 79);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 79);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 79);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 79);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 79);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 79);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 79);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 79);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 79);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 79);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 79);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 79);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 79);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 79);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 79);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 79);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 79);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 79);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang79_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 79);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  Future<void> hamKhoiTaoToaDoChiTietHang80() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 80);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 80);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 80);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 80);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 80);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 80);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 80);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 80);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 80);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 80);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 80);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 80);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 80);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 80);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 80);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 80);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 80);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 80);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 80);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 80);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 80);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 80);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 80);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 80);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 80);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 80);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 80);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 80);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 80);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 80);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 80);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 80);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 80);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 80);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 80);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 80);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 80);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 80);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 80);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 80);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 80);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 80);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 80);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 80);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 80);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 80);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 80);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 80);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 80);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 80);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 80);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 80);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 80);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 80);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang80_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 80);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }
}
