import 'package:pkg_dinh_nghia_ss020/dinh_nghia_thanh_phan_define.dart';
/// -----
/// TODO:
/// -----
class DiemToaDoChiTietPhamViDenHang90 {
  List<DiemToaDoCoBan> danhSachToaDo = [];

  Future<void> onInitList() async {
    await hamKhoiTaoToaDoChiTietHang81();
    await hamKhoiTaoToaDoChiTietHang82();
    await hamKhoiTaoToaDoChiTietHang83();
    await hamKhoiTaoToaDoChiTietHang84();
    await hamKhoiTaoToaDoChiTietHang85();
    await hamKhoiTaoToaDoChiTietHang86();
    await hamKhoiTaoToaDoChiTietHang87();
    await hamKhoiTaoToaDoChiTietHang88();
    await hamKhoiTaoToaDoChiTietHang89();
    await hamKhoiTaoToaDoChiTietHang90();
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang81() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 81);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 81);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 81);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 81);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 81);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 81);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 81);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 81);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 81);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 81);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 81);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 81);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 81);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 81);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 81);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 81);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 81);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 81);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 81);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 81);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 81);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 81);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 81);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 81);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 81);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 81);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 81);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 81);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 81);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 81);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 81);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 81);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 81);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 81);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 81);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 81);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 81);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 81);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 81);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 81);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 81);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 81);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 81);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 81);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 81);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 81);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 81);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 81);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 81);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 81);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 81);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 81);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 81);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 81);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang81_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 81);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang82() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 82);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 82);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 82);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 82);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 82);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 82);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 82);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 82);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 82);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 82);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 82);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 82);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 82);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 82);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 82);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 82);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 82);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 82);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 82);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 82);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 82);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 82);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 82);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 82);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 82);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 82);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 82);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 82);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 82);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 82);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 82);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 82);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 82);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 82);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 82);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 82);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 82);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 82);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 82);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 82);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 82);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 82);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 82);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 82);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 82);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 82);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 82);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 82);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 82);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 82);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 82);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 82);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 82);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 82);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang82_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 82);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang83() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 83);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 83);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 83);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 83);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 83);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 83);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 83);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 83);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 83);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 83);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 83);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 83);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 83);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 83);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 83);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 83);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 83);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 83);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 83);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 83);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 83);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 83);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 83);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 83);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 83);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 83);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 83);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 83);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 83);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 83);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 83);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 83);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 83);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 83);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 83);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 83);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 83);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 83);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 83);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 83);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 83);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 83);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 83);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 83);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 83);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 83);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 83);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 83);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 83);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 83);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 83);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 83);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 83);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 83);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang83_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 83);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang84() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 84);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 84);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 84);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 84);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 84);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 84);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 84);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 84);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 84);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 84);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 84);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 84);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 84);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 84);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 84);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 84);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 84);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 84);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 84);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 84);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 84);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 84);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 84);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 84);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 84);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 84);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 84);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 84);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 84);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 84);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 84);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 84);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 84);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 84);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 84);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 84);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 84);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 84);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 84);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 84);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 84);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 84);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 84);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 84);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 84);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 84);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 84);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 84);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 84);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 84);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 84);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 84);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 84);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 84);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang84_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 84);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang85() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 85);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 85);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 85);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 85);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 85);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 85);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 85);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 85);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 85);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 85);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 85);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 85);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 85);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 85);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 85);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 85);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 85);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 85);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 85);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 85);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 85);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 85);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 85);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 85);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 85);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 85);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 85);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 85);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 85);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 85);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 85);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 85);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 85);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 85);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 85);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 85);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 85);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 85);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 85);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 85);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 85);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 85);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 85);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 85);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 85);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 85);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 85);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 85);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 85);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 85);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 85);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 85);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 85);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 85);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang85_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 85);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang86() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 86);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 86);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 86);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 86);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 86);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 86);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 86);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 86);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 86);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 86);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 86);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 86);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 86);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 86);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 86);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 86);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 86);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 86);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 86);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 86);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 86);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 86);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 86);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 86);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 86);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 86);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 86);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 86);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 86);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 86);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 86);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 86);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 86);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 86);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 86);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 86);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 86);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 86);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 86);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 86);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 86);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 86);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 86);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 86);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 86);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 86);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 86);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 86);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 86);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 86);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 86);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 86);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 86);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 86);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang86_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 86);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang87() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 87);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 87);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 87);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 87);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 87);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 87);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 87);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 87);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 87);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 87);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 87);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 87);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 87);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 87);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 87);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 87);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 87);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 87);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 87);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 87);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 87);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 87);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 87);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 87);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 87);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 87);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 87);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 87);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 87);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 87);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 87);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 87);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 87);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 87);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 87);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 87);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 87);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 87);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 87);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 87);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 87);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 87);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 87);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 87);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 87);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 87);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 87);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 87);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 87);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 87);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 87);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 87);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 87);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 87);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang87_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 87);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang88() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 88);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 88);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 88);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 88);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 88);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 88);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 88);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 88);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 88);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 88);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 88);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 88);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 88);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 88);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 88);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 88);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 88);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 88);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 88);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 88);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 88);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 88);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 88);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 88);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 88);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 88);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 88);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 88);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 88);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 88);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 88);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 88);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 88);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 88);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 88);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 88);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 88);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 88);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 88);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 88);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 88);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 88);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 88);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 88);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 88);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 88);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 88);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 88);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 88);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 88);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 88);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 88);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 88);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 88);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang88_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 88);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang89() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 89);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 89);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 89);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 89);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 89);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 89);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 89);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 89);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 89);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 89);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 89);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 89);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 89);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 89);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 89);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 89);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 89);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 89);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 89);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 89);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 89);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 89);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 89);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 89);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 89);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 89);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 89);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 89);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 89);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 89);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 89);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 89);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 89);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 89);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 89);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 89);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 89);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 89);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 89);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 89);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 89);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 89);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 89);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 89);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 89);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 89);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 89);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 89);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 89);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 89);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 89);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 89);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 89);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 89);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang89_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 89);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  Future<void> hamKhoiTaoToaDoChiTietHang90() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 90);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 90);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 90);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 90);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 90);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 90);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 90);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 90);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 90);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 90);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 90);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 90);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 90);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 90);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 90);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 90);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 90);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 90);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 90);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 90);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 90);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 90);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 90);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 90);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 90);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 90);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 90);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 90);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 90);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 90);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 90);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 90);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 90);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 90);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 90);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 90);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 90);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 90);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 90);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 90);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 90);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 90);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 90);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 90);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 90);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 90);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 90);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 90);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 90);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 90);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 90);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 90);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 90);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 90);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang90_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 90);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }
}
