import 'package:pkg_dinh_nghia_ss020/dinh_nghia_thanh_phan_define.dart';
/// -----
/// TODO:
/// -----
class DiemToaDoChiTietPhamViDenHang10 {
  List<DiemToaDoCoBan> danhSachToaDo = [];

  Future<void> onInitList() async {
    await hamKhoiTaoToaDoChiTietHang00();
    await hamKhoiTaoToaDoChiTietHang01();
    await hamKhoiTaoToaDoChiTietHang02();
    await hamKhoiTaoToaDoChiTietHang03();
    await hamKhoiTaoToaDoChiTietHang04();
    await hamKhoiTaoToaDoChiTietHang05();
    await hamKhoiTaoToaDoChiTietHang06();
    await hamKhoiTaoToaDoChiTietHang07();
    await hamKhoiTaoToaDoChiTietHang08();
    await hamKhoiTaoToaDoChiTietHang09();
    await hamKhoiTaoToaDoChiTietHang10();
    return;
  }

  Future<void> hamKhoiTaoToaDoChiTietHang00() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 0);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 0);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 0);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 0);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 0);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 0);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 0);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 0);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 0);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 0);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 0);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 0);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 0);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 0);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 0);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 0);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 0);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 0);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 0);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 0);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 0);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 0);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 0);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 0);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 0);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 0);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 0);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 0);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 0);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 0);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 0);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 0);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 0);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 0);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 0);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 0);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 0);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 0);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 0);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 0);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 0);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 0);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 0);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 0);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 0);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 0);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 0);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 0);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 0);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 0);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 0);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 0);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 0);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 0);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang0_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 0);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang01() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 1);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 1);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 1);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 1);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 1);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 1);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 1);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 1);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 1);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 1);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 1);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 1);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 1);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 1);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 1);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 1);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 1);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 1);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 1);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 1);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 1);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 1);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 1);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 1);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 1);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 1);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 1);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 1);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 1);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 1);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 1);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 1);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 1);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 1);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 1);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 1);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 1);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 1);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 1);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 1);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 1);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 1);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 1);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 1);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 1);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 1);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 1);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 1);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 1);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 1);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 1);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 1);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 1);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 1);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang1_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 1);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang02() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 2);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 2);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 2);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 2);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 2);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 2);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 2);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 2);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 2);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 2);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 2);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 2);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 2);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 2);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 2);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 2);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 2);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 2);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 2);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 2);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 2);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 2);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 2);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 2);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 2);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 2);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 2);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 2);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 2);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 2);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 2);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 2);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 2);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 2);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 2);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 2);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 2);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 2);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 2);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 2);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 2);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 2);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 2);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 2);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 2);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 2);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 2);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 2);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 2);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 2);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 2);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 2);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 2);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 2);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang2_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 2);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang03() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 3);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 3);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 3);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 3);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 3);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 3);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 3);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 3);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 3);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 3);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 3);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 3);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 3);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 3);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 3);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 3);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 3);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 3);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 3);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 3);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 3);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 3);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 3);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 3);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 3);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 3);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 3);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 3);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 3);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 3);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 3);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 3);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 3);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 3);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 3);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 3);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 3);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 3);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 3);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 3);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 3);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 3);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 3);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 3);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 3);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 3);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 3);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 3);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 3);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 3);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 3);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 3);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 3);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 3);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang3_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 3);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang04() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 4);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 4);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 4);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 4);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 4);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 4);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 4);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 4);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 4);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 4);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 4);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 4);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 4);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 4);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 4);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 4);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 4);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 4);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 4);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 4);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 4);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 4);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 4);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 4);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 4);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 4);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 4);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 4);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 4);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 4);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 4);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 4);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 4);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 4);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 4);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 4);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 4);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 4);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 4);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 4);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 4);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 4);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 4);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 4);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 4);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 4);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 4);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 4);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 4);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 4);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 4);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 4);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 4);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 4);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang4_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 4);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang05() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 5);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 5);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 5);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 5);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 5);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 5);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 5);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 5);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 5);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 5);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 5);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 5);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 5);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 5);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 5);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 5);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 5);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 5);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 5);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 5);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 5);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 5);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 5);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 5);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 5);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 5);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 5);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 5);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 5);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 5);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 5);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 5);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 5);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 5);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 5);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 5);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 5);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 5);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 5);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 5);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 5);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 5);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 5);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 5);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 5);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 5);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 5);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 5);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 5);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 5);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 5);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 5);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 5);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 5);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang5_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 5);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang06() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 6);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 6);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 6);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 6);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 6);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 6);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 6);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 6);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 6);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 6);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 6);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 6);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 6);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 6);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 6);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 6);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 6);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 6);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 6);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 6);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 6);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 6);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 6);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 6);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 6);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 6);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 6);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 6);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 6);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 6);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 6);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 6);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 6);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 6);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 6);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 6);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 6);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 6);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 6);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 6);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 6);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 6);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 6);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 6);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 6);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 6);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 6);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 6);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 6);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 6);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 6);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 6);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 6);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 6);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang6_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 6);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang07() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 7);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 7);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 7);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 7);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 7);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 7);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 7);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 7);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 7);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 7);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 7);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 7);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 7);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 7);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 7);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 7);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 7);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 7);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 7);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 7);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 7);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 7);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 7);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 7);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 7);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 7);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 7);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 7);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 7);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 7);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 7);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 7);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 7);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 7);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 7);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 7);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 7);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 7);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 7);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 7);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 7);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 7);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 7);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 7);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 7);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 7);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 7);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 7);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 7);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 7);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 7);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 7);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 7);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 7);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang7_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 7);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang08() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 8);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 8);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 8);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 8);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 8);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 8);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 8);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 8);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 8);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 8);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 8);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 8);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 8);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 8);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 8);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 8);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 8);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 8);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 8);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 8);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 8);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 8);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 8);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 8);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 8);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 8);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 8);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 8);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 8);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 8);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 8);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 8);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 8);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 8);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 8);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 8);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 8);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 8);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 8);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 8);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 8);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 8);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 8);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 8);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 8);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 8);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 8);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 8);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 8);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 8);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 8);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 8);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 8);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 8);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang8_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 8);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  ///
  ///
  ///
  Future<void> hamKhoiTaoToaDoChiTietHang09() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 9);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 9);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 9);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 9);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 9);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 9);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 9);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 9);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 9);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 9);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 9);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 9);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 9);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 9);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 9);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 9);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 9);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 9);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 9);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 9);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 9);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 9);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 9);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 9);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 9);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 9);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 9);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 9);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 9);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 9);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 9);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 9);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 9);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 9);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 9);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 9);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 9);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 9);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 9);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 9);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 9);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 9);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 9);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 9);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 9);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 9);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 9);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 9);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 9);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 9);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 9);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 9);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 9);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 9);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang9_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 9);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }

  Future<void> hamKhoiTaoToaDoChiTietHang10() async {
    DiemToaDoCoBan toaDo00 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot0]', moTa: '', xRangeValue: 0, yRangeValue: 10);
    DiemToaDoCoBan toaDo01 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot1]', moTa: '', xRangeValue: 1, yRangeValue: 10);
    DiemToaDoCoBan toaDo02 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot2]', moTa: '', xRangeValue: 2, yRangeValue: 10);
    DiemToaDoCoBan toaDo03 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot3]', moTa: '', xRangeValue: 3, yRangeValue: 10);
    DiemToaDoCoBan toaDo04 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot4]', moTa: '', xRangeValue: 4, yRangeValue: 10);
    DiemToaDoCoBan toaDo05 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot5]', moTa: '', xRangeValue: 5, yRangeValue: 10);
    DiemToaDoCoBan toaDo06 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot6]', moTa: '', xRangeValue: 6, yRangeValue: 10);
    DiemToaDoCoBan toaDo07 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot7]', moTa: '', xRangeValue: 7, yRangeValue: 10);
    DiemToaDoCoBan toaDo08 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot8]', moTa: '', xRangeValue: 8, yRangeValue: 10);
    DiemToaDoCoBan toaDo09 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot9]', moTa: '', xRangeValue: 9, yRangeValue: 10);
    DiemToaDoCoBan toaDo10 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot10]', moTa: '', xRangeValue: 10, yRangeValue: 10);
    DiemToaDoCoBan toaDo11 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot11]', moTa: '', xRangeValue: 11, yRangeValue: 10);
    DiemToaDoCoBan toaDo12 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot12]', moTa: '', xRangeValue: 12, yRangeValue: 10);
    DiemToaDoCoBan toaDo13 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot13]', moTa: '', xRangeValue: 13, yRangeValue: 10);
    DiemToaDoCoBan toaDo14 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot14]', moTa: '', xRangeValue: 14, yRangeValue: 10);
    DiemToaDoCoBan toaDo15 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot15]', moTa: '', xRangeValue: 15, yRangeValue: 10);
    DiemToaDoCoBan toaDo16 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot16]', moTa: '', xRangeValue: 16, yRangeValue: 10);
    DiemToaDoCoBan toaDo17 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot17]', moTa: '', xRangeValue: 17, yRangeValue: 10);
    DiemToaDoCoBan toaDo18 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot18]', moTa: '', xRangeValue: 18, yRangeValue: 10);
    DiemToaDoCoBan toaDo19 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot19]', moTa: '', xRangeValue: 19, yRangeValue: 10);
    DiemToaDoCoBan toaDo20 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot20]', moTa: '', xRangeValue: 20, yRangeValue: 10);
    DiemToaDoCoBan toaDo21 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot21]', moTa: '', xRangeValue: 21, yRangeValue: 10);
    DiemToaDoCoBan toaDo22 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot22]', moTa: '', xRangeValue: 22, yRangeValue: 10);
    DiemToaDoCoBan toaDo23 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot23]', moTa: '', xRangeValue: 23, yRangeValue: 10);
    DiemToaDoCoBan toaDo24 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot24]', moTa: '', xRangeValue: 24, yRangeValue: 10);
    DiemToaDoCoBan toaDo25 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot25]', moTa: '', xRangeValue: 25, yRangeValue: 10);
    DiemToaDoCoBan toaDo26 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot26]', moTa: '', xRangeValue: 26, yRangeValue: 10);
    DiemToaDoCoBan toaDo27 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot27]', moTa: '', xRangeValue: 27, yRangeValue: 10);
    DiemToaDoCoBan toaDo28 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot28]', moTa: '', xRangeValue: 28, yRangeValue: 10);
    DiemToaDoCoBan toaDo29 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot29]', moTa: '', xRangeValue: 29, yRangeValue: 10);
    DiemToaDoCoBan toaDo30 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot30]', moTa: '', xRangeValue: 30, yRangeValue: 10);
    DiemToaDoCoBan toaDo31 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot31]', moTa: '', xRangeValue: 31, yRangeValue: 10);
    DiemToaDoCoBan toaDo32 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot32]', moTa: '', xRangeValue: 32, yRangeValue: 10);
    DiemToaDoCoBan toaDo33 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot33]', moTa: '', xRangeValue: 33, yRangeValue: 10);
    DiemToaDoCoBan toaDo34 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot34]', moTa: '', xRangeValue: 34, yRangeValue: 10);
    DiemToaDoCoBan toaDo35 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot35]', moTa: '', xRangeValue: 35, yRangeValue: 10);
    DiemToaDoCoBan toaDo36 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot36]', moTa: '', xRangeValue: 36, yRangeValue: 10);
    DiemToaDoCoBan toaDo37 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot37]', moTa: '', xRangeValue: 37, yRangeValue: 10);
    DiemToaDoCoBan toaDo38 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot38]', moTa: '', xRangeValue: 38, yRangeValue: 10);
    DiemToaDoCoBan toaDo39 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot39]', moTa: '', xRangeValue: 39, yRangeValue: 10);
    DiemToaDoCoBan toaDo40 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot40]', moTa: '', xRangeValue: 40, yRangeValue: 10);
    DiemToaDoCoBan toaDo41 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot41]', moTa: '', xRangeValue: 41, yRangeValue: 10);
    DiemToaDoCoBan toaDo42 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot42]', moTa: '', xRangeValue: 42, yRangeValue: 10);
    DiemToaDoCoBan toaDo43 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot43]', moTa: '', xRangeValue: 43, yRangeValue: 10);
    DiemToaDoCoBan toaDo44 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot44]', moTa: '', xRangeValue: 44, yRangeValue: 10);
    DiemToaDoCoBan toaDo45 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot45]', moTa: '', xRangeValue: 45, yRangeValue: 10);
    DiemToaDoCoBan toaDo46 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot46]', moTa: '', xRangeValue: 46, yRangeValue: 10);
    DiemToaDoCoBan toaDo47 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot47]', moTa: '', xRangeValue: 47, yRangeValue: 10);
    DiemToaDoCoBan toaDo48 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot48]', moTa: '', xRangeValue: 48, yRangeValue: 10);
    DiemToaDoCoBan toaDo49 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot49]', moTa: '', xRangeValue: 49, yRangeValue: 10);
    DiemToaDoCoBan toaDo50 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot50]', moTa: '', xRangeValue: 50, yRangeValue: 10);
    DiemToaDoCoBan toaDo51 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot51]', moTa: '', xRangeValue: 51, yRangeValue: 10);
    DiemToaDoCoBan toaDo52 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot52]', moTa: '', xRangeValue: 52, yRangeValue: 10);
    DiemToaDoCoBan toaDo53 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot53]', moTa: '', xRangeValue: 53, yRangeValue: 10);
    DiemToaDoCoBan toaDo54 = DiemToaDoCoBan(maDinhDanh: '[hang10_cot54]', moTa: '', xRangeValue: 54, yRangeValue: 10);

    danhSachToaDo.add(toaDo00);
    danhSachToaDo.add(toaDo01);
    danhSachToaDo.add(toaDo02);
    danhSachToaDo.add(toaDo03);
    danhSachToaDo.add(toaDo04);
    danhSachToaDo.add(toaDo05);
    danhSachToaDo.add(toaDo06);
    danhSachToaDo.add(toaDo07);
    danhSachToaDo.add(toaDo08);
    danhSachToaDo.add(toaDo09);
    danhSachToaDo.add(toaDo10);
    danhSachToaDo.add(toaDo11);
    danhSachToaDo.add(toaDo12);
    danhSachToaDo.add(toaDo13);
    danhSachToaDo.add(toaDo14);
    danhSachToaDo.add(toaDo15);
    danhSachToaDo.add(toaDo16);
    danhSachToaDo.add(toaDo17);
    danhSachToaDo.add(toaDo18);
    danhSachToaDo.add(toaDo19);
    danhSachToaDo.add(toaDo20);
    danhSachToaDo.add(toaDo21);
    danhSachToaDo.add(toaDo22);
    danhSachToaDo.add(toaDo23);
    danhSachToaDo.add(toaDo24);
    danhSachToaDo.add(toaDo25);
    danhSachToaDo.add(toaDo26);
    danhSachToaDo.add(toaDo27);
    danhSachToaDo.add(toaDo28);
    danhSachToaDo.add(toaDo29);
    danhSachToaDo.add(toaDo30);
    danhSachToaDo.add(toaDo31);
    danhSachToaDo.add(toaDo32);
    danhSachToaDo.add(toaDo33);
    danhSachToaDo.add(toaDo34);
    danhSachToaDo.add(toaDo35);
    danhSachToaDo.add(toaDo36);
    danhSachToaDo.add(toaDo37);
    danhSachToaDo.add(toaDo38);
    danhSachToaDo.add(toaDo39);
    danhSachToaDo.add(toaDo40);
    danhSachToaDo.add(toaDo41);
    danhSachToaDo.add(toaDo42);
    danhSachToaDo.add(toaDo43);
    danhSachToaDo.add(toaDo44);
    danhSachToaDo.add(toaDo45);
    danhSachToaDo.add(toaDo46);
    danhSachToaDo.add(toaDo47);
    danhSachToaDo.add(toaDo48);
    danhSachToaDo.add(toaDo49);
    danhSachToaDo.add(toaDo50);
    danhSachToaDo.add(toaDo51);
    danhSachToaDo.add(toaDo52);
    danhSachToaDo.add(toaDo53);
    danhSachToaDo.add(toaDo54);
    return;
  }
}
