name: pkg_chua_cap_nhat
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pkg_dinh_nghia_ss020:
    path: ../pkg_dinh_nghia_ss020
  pkg_dinh_nghia_ss022:
    path: ../pkg_dinh_nghia_ss022
  pkg_dinh_nghia_ss024:
    path: ../pkg_dinh_nghia_ss024
  pkg_dinh_nghia_ss026:
    path: ../pkg_dinh_nghia_ss026
  pkg_dinh_nghia_ss028:
    path: ../pkg_dinh_nghia_ss028
  pkg_dinh_nghia_ss030:
    path: ../pkg_dinh_nghia_ss030
  pkg_dinh_nghia_ss032:
    path: ../pkg_dinh_nghia_ss032
  pkg_dinh_nghia_ss034:
    path: ../pkg_dinh_nghia_ss034
  pkg_dinh_nghia_ss036:
    path: ../pkg_dinh_nghia_ss036
  pkg_dinh_nghia_ss038:
    path: ../pkg_dinh_nghia_ss038
  pkg_dinh_nghia_ss040:
    path: ../pkg_dinh_nghia_ss040
  pkg_dinh_nghia_ss042:
    path: ../pkg_dinh_nghia_ss042
  pkg_dinh_nghia_ss044:
    path: ../pkg_dinh_nghia_ss044
  pkg_dinh_nghia_ss046:
    path: ../pkg_dinh_nghia_ss046
  pkg_dinh_nghia_ss048:
    path: ../pkg_dinh_nghia_ss048
  pkg_dinh_nghia_ss050:
    path: ../pkg_dinh_nghia_ss050

  pkg_man_hinh_ss00020:
    path: ../pkg_man_hinh_ss00020
  pkg_man_hinh_ss00022:
    path: ../pkg_man_hinh_ss00022
  pkg_man_hinh_ss00024:
    path: ../pkg_man_hinh_ss00024
  pkg_man_hinh_ss00026:
    path: ../pkg_man_hinh_ss00026
  pkg_man_hinh_ss00028:
    path: ../pkg_man_hinh_ss00028
  pkg_man_hinh_ss00030:
    path: ../pkg_man_hinh_ss00030
  pkg_man_hinh_ss00032:
    path: ../pkg_man_hinh_ss00032
  pkg_man_hinh_ss00034:
    path: ../pkg_man_hinh_ss00034
  pkg_man_hinh_ss00090:
    path: ../pkg_man_hinh_ss00090

  animate_do: 3.0.2
  cupertino_icons: ^1.0.6
  #  audioplayers: 6.0.0
  collection: 1.19.1
  carousel_slider: 4.2.1
  go_router: 14.0.0
  provider: 6.0.2
  shared_preferences: 2.0.13
  #  sqflite: 2.3.0
  path: 1.9.0
  #  google_mobile_ads: 5.0.0
  google_fonts: 5.0.0
  flame: 1.25.0
  #  vm_service: 14.2.1
  video_player: 2.9.3

dev_dependencies:
  #  flutter_test:
  #    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    - assets/images/
    - assets/images/RootMd/0002_TruyCap_1/00001_TruyCap_2/000001_TruyCap_3/0000001_TruyCap_4/00000001_TruyCap_5/000000001_TruyCap_6/R000000000_TruyCap_7/nut_bam.png
    - assets/images/RootMd/0002_TruyCap_1/00002_TruyCap_2/000001_TruyCap_3/0000001_TruyCap_4/00000001_TruyCap_5/000000001_TruyCap_6/R000000000_TruyCap_7/nut_bam.png
    - assets/images/RootMd/0002_TruyCap_1/00003_TruyCap_2/000001_TruyCap_3/0000001_TruyCap_4/00000001_TruyCap_5/000000001_TruyCap_6/R000000000_TruyCap_7/nut_bam.png
    - assets/images/RootMd/0002_TruyCap_1/00004_TruyCap_2/000001_TruyCap_3/0000001_TruyCap_4/00000001_TruyCap_5/000000001_TruyCap_6/R000000000_TruyCap_7/nut_bam.png
    - assets/images/RootMd/0002_TruyCap_1/00005_TruyCap_2/000001_TruyCap_3/0000001_TruyCap_4/00000001_TruyCap_5/000000001_TruyCap_6/R000000000_TruyCap_7/nut_bam.png

    # Video Man Hinh Khoi Dong
    - assets/images/01_Man_Hinh/Screen01/08_SubComs/Com01/08_SubComs/Com02/08_SubComs/Com03/Com01/video_800.mp4

    # Hinh Anh Khung Nen Man Hinh Cap Mot
    # _____[Man_Hinh_Chuc_Nang_Cua_Hang]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com01/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com01/hinh_anh_khung_nen_man_hinh.png
    # _____[Man_Hinh_Chuc_Nang_Thanh_Tich]_____
    - assets/images/01_Man_Hinh/Screen04/08_SubComs/Com01/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com01/hinh_anh_khung_nen_man_hinh.png
    # _____[Man_Hinh_Chuc_Nang_Chien_Dau]_____
    - assets/images/01_Man_Hinh/Screen04/08_SubComs/Com01/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com01/hinh_anh_khung_nen_man_hinh.png
    # _____[Man_Hinh_Chuc_Nang_Thong_Tin]_____
    - assets/images/01_Man_Hinh/Screen04/08_SubComs/Com01/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com01/hinh_anh_khung_nen_man_hinh.png
    # _____[Man_Hinh_Chuc_Nang_Cai_Dat]_____
    - assets/images/01_Man_Hinh/Screen07/08_SubComs/Com01/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com01/hinh_anh_khung_nen_man_hinh.png

    # Hinh Anh Nut Bam Dong Man Hinh Cap Mot
    # _____[Man_Hinh_Chinh]_____
    - assets/images/01_Man_Hinh/Screen02/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com02/hinh_anh_nut_bam_dong_man_hinh.png
    # _____[Man_Hinh_Chuc_Nang_Cua_Hang]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com02/hinh_anh_nut_bam_dong_man_hinh.png
    # _____[Man_Hinh_Chuc_Nang_Thanh_Tich]_____
    - assets/images/01_Man_Hinh/Screen04/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com02/hinh_anh_nut_bam_dong_man_hinh.png
    # _____[Man_Hinh_Chuc_Nang_Chien_Dau]_____
    - assets/images/01_Man_Hinh/Screen05/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com02/hinh_anh_nut_bam_dong_man_hinh.png
    # _____[Man_Hinh_Chuc_Nang_Thong_Tin]_____
    - assets/images/01_Man_Hinh/Screen06/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com02/hinh_anh_nut_bam_dong_man_hinh.png
    # _____[Man_Hinh_Chuc_Nang_Cai_Dat]_____
    - assets/images/01_Man_Hinh/Screen07/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com02/hinh_anh_nut_bam_dong_man_hinh.png

    # _____[Nut_Bam_Chuyen_Man_Hinh_Chien_Binh]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/nut_bam_chuyen_man_hinh_chien_binh.png
    # _____[Nut_Bam_Chuyen_Man_Hinh_Vat_Pham]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com02/nut_bam_chuyen_man_hinh_vat_pham.png

    # [Hinh_Anh_Khung_Nen_The_Chien_Binh]
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00E03_SS01]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/hinh_anh_khung_nen_the_chien_binh_00E03SS01.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00E03_SS02]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com02/hinh_anh_khung_nen_the_chien_binh_00E03SS02.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00E03_SS03]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com03/hinh_anh_khung_nen_the_chien_binh_00E03SS03.png

    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00D04_SS01]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com02/08_SubComs/Com01/hinh_anh_khung_nen_the_chien_binh_00D04SS01.png

    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00C05_SS01]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com03/08_SubComs/Com01/hinh_anh_khung_nen_the_chien_binh_00C05SS01.png

    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00B06_SS01]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com04/08_SubComs/Com01/hinh_anh_khung_nen_the_chien_binh_00B06SS01.png

    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00A07_SS01]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com05/08_SubComs/Com01/hinh_anh_khung_nen_the_chien_binh_00A07SS01.png

    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00S08_SS01]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com06/08_SubComs/Com01/hinh_anh_khung_nen_the_chien_binh_00S08SS01.png

    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_0SS09_SS01]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com07/08_SubComs/Com01/hinh_anh_khung_nen_the_chien_binh_0SS09SS01.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_0SS09_SS02]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com07/08_SubComs/Com02/hinh_anh_khung_nen_the_chien_binh_0SS09SS02.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_0SS09_SS03]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com07/08_SubComs/Com03/hinh_anh_khung_nen_the_chien_binh_0SS09SS03.png

    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS01]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com08/08_SubComs/Com01/hinh_anh_khung_nen_the_chien_binh_SSS10SS01.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS02]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com08/08_SubComs/Com02/hinh_anh_khung_nen_the_chien_binh_SSS10SS02.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS03]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com08/08_SubComs/Com03/hinh_anh_khung_nen_the_chien_binh_SSS10SS03.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS04]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com08/08_SubComs/Com04/hinh_anh_khung_nen_the_chien_binh_SSS10SS04.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS05]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com01/08_SubComs/Com08/08_SubComs/Com05/hinh_anh_khung_nen_the_chien_binh_SSS10SS05.png

    # _____[Hinh_Anh_Nut_Bam_Gia_Tri_Trao_Doi_The_Chien_Binh]_____
    - assets/images/01_Man_Hinh/Screen03/08_SubComs/Com02/08_SubComs/Com02/08_SubComs/Com01/hinh_anh_nut_bam_gia_tri_trao_doi_the_chien_binh.png


    # _____[Man_Hinh_Chuc_Nang_Chien_Dau]_____
    # _____[Nut_Bam_Trien_Khai_Chien_Dau]_____
    - assets/images/01_Man_Hinh/Screen05/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com03/hinh_anh_nut_bam_trien_khai_chien_dau.png
    # _____[Nut_Bam_Chuyen_Chon_Trai]_____
    - assets/images/01_Man_Hinh/Screen05/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com04/hinh_anh_nut_bam_chuyen_chon_trai.png
    # _____[Nut_Bam_Chuyen_Chon_Phai]_____
    - assets/images/01_Man_Hinh/Screen05/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com01/08_SubComs/Com05/hinh_anh_nut_bam_chuyen_chon_phai.png

    # _____[Man_Hinh_Chuc_Nang_Chien_Dau]_____
    # _____[Man_Hinh_Hangar_Danh_Sach_Chon_Chien_Dau_Co]_____
    # _____[The_Thong_Tin_Chien_Dau_Co]_____
    # _____[Khung_Hinh_The_Thong_Tin_Chien_Dau_Co]_____
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00E03_SS01]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com10/08_SubComs/Com10/hinh_anh_khung_hinh_the_thong_tin_00E03SS01.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00E03_SS02]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com10/08_SubComs/Com20/hinh_anh_khung_hinh_the_thong_tin_00E03SS02.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00E03_SS03]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com10/08_SubComs/Com30/hinh_anh_khung_hinh_the_thong_tin_00E03SS03.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00D04_SS01]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com20/08_SubComs/Com10/hinh_anh_khung_hinh_the_thong_tin_00D04SS01.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00C05_SS01]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com30/08_SubComs/Com10/hinh_anh_khung_hinh_the_thong_tin_00C05SS01.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00B06_SS01]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com40/08_SubComs/Com10/hinh_anh_khung_hinh_the_thong_tin_00B06SS01.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00A07_SS01]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com50/08_SubComs/Com10/hinh_anh_khung_hinh_the_thong_tin_00A07SS01.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_00S08_SS01]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com60/08_SubComs/Com10/hinh_anh_khung_hinh_the_thong_tin_00S08SS01.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_0SS09_SS01]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com70/08_SubComs/Com10/hinh_anh_khung_hinh_the_thong_tin_0SS09SS01.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_0SS09_SS02]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com70/08_SubComs/Com20/hinh_anh_khung_hinh_the_thong_tin_0SS09SS02.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_0SS09_SS03]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com70/08_SubComs/Com30/hinh_anh_khung_hinh_the_thong_tin_0SS09SS03.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS01]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com80/08_SubComs/Com10/hinh_anh_khung_hinh_the_thong_tin_SSS10SS01.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS02]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com80/08_SubComs/Com20/hinh_anh_khung_hinh_the_thong_tin_SSS10SS02.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS03]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com80/08_SubComs/Com30/hinh_anh_khung_hinh_the_thong_tin_SSS10SS03.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS04]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com80/08_SubComs/Com40/hinh_anh_khung_hinh_the_thong_tin_SSS10SS04.png
    # _____[CHIEN_DAU_CO_DANG_CAP_SAO_SSS10_SS05]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com12/08_SubComs/Com10/08_SubComs/Com80/08_SubComs/Com50/hinh_anh_khung_hinh_the_thong_tin_SSS10SS05.png

    # _____[Nut_Bam_Chuyen_Che_Do_Hien_Thi]_____
    # _____[Nut_Bam_Thong_Tin_Chien_Dau_Co]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com40/nut_bam_thong_tin_chien_dau_co.png
    # _____[Nut_Bam_Nang_Cap_Chien_Dau_Co]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen10/06_Coms/Com50/nut_bam_nang_cap_chien_dau_co.png

    # _____[Khung_Hinh_The_Hangar_Ban_Do_Chien_Dau]_____
    # _____[Ban_Do_Chien_Dau_SS01]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen20/06_Coms/Com10/08_SubComs/Com10/08_SubComs/Com10/hinh_anh_khung_hinh_the_hangar_ban_do_chien_dau_ss01.png
    # _____[Ban_Do_Chien_Dau_SS02]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen20/06_Coms/Com10/08_SubComs/Com10/08_SubComs/Com20/hinh_anh_khung_hinh_the_hangar_ban_do_chien_dau_ss02.png
    # _____[Ban_Do_Chien_Dau_SS03]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen20/06_Coms/Com10/08_SubComs/Com10/08_SubComs/Com30/hinh_anh_khung_hinh_the_hangar_ban_do_chien_dau_ss03.png
    # _____[Ban_Do_Chien_Dau_SS04]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen20/06_Coms/Com10/08_SubComs/Com10/08_SubComs/Com40/hinh_anh_khung_hinh_the_hangar_ban_do_chien_dau_ss04.png
    # _____[Ban_Do_Chien_Dau_SS05]_____
    - assets/images/Ms_30a/08_SubScrs/Screen20/08_SubScrs/Screen20/06_Coms/Com10/08_SubComs/Com10/08_SubComs/Com50/hinh_anh_khung_hinh_the_hangar_ban_do_chien_dau_ss05.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
